from opentargets_pharmgkb.variant_annotations import get_variant_annotations, associate_annotations_with_alleles


def test_get_variant_annotations():
    clinical_alleles_df = ...
    clinical_evidence_df = ...
    var_annotations_df = ...
    expected_df = ...
    assert get_variant_annotations(clinical_alleles_df, clinical_evidence_df, var_annotations_df) == expected_df


def test_associate_annotations_with_alleles():
    clinical_alleles_df = ...
    var_annotations_df = ...
    expected_df = ...
    assert associate_annotations_with_alleles(var_annotations_df, clinical_alleles_df) == expected_df
